# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goginit < Formula
  desc ""
  homepage "https://github.com/pol-cova/goginit"
  version "0.1.2"

  on_macos do
    url "https://github.com/pol-cova/GoGinit/releases/download/v0.1.2/GoGinit_0.1.2_darwin_all.tar.gz"
    sha256 "df01a3a6a7f2f4da8370b454ca37419f6466707c1bb7fb7b276e9194206386c0"

    def install
      bin.install "GoGinit"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pol-cova/GoGinit/releases/download/v0.1.2/GoGinit_0.1.2_linux_amd64.tar.gz"
        sha256 "ea856f77660af6a23f2d61f221db6ffe84bcfc54d34bf26c9983c3032969ad4e"

        def install
          bin.install "goginit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pol-cova/GoGinit/releases/download/v0.1.2/GoGinit_0.1.2_linux_arm64.tar.gz"
        sha256 "7ad86e5cc3467322a2fd5c0205e1734967675224a068be66f2265cc62ed39fe4"

        def install
          bin.install "goginit"
        end
      end
    end
  end
end
