# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goginit < Formula
  desc ""
  homepage "https://github.com/pol-cova/goginit"
  version "0.2.1"

  on_macos do
    url "https://github.com/pol-cova/GoGinit/releases/download/v0.2.1/GoGinit_0.2.1_darwin_all.tar.gz"
    sha256 "e3007d3ad2746ad21a9e792194a7fe92b227d2d252260ed542933df11236346c"

    def install
      bin.install "GoGinit"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pol-cova/GoGinit/releases/download/v0.2.1/GoGinit_0.2.1_linux_amd64.tar.gz"
        sha256 "fbb7d5df961e531b29800f964836f74232bae35a91b54281941522b9579e5b30"

        def install
          bin.install "goginit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pol-cova/GoGinit/releases/download/v0.2.1/GoGinit_0.2.1_linux_arm64.tar.gz"
        sha256 "6c8ecaed912d3539368243a172109930f0c83f60df3f77f9c98d7d2241c87596"

        def install
          bin.install "goginit"
        end
      end
    end
  end
end
